name: Java Maven CI workflow

on:
  push:
    branches: [ master ]    # Runs when you push to main
  pull_request:
    branches: [ master ]    # Runs when a PR targets main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: maven

      # Step 3: Build and test
      - name: Build with Maven
        run: mvn clean package -B
        
      # Step 4: Trivy Scan
      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with: 
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          
      # Step 4: Upload build artifacts
      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-maven-artefact
          path: target/*.war
